# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build Present

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
    paths:
      - '**'
      - '!README.md'
      - '!**.yml'
  pull_request:
    branches: 
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install nodeppt
      run: |
       npm install -g nodeppt
       rm -rf dist
       nodeppt build index.md
       nodeppt build repos.md
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PPT_DEPLOY }}
        publish_dir: ./dist
        commit_message: ${{ github.event.head_commit.message }}
